version: '3'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:3.4.3.Final
    environment:
      # 初回起動時のみコメントアウトを外す
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
      - POSTGRES_PORT=5432
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      # この環境変数がないとエラーになる
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
    ports:
      - 8080:8080
    networks:
      backend:
  postgres:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - v-postgres:/var/lib/postgresql/data
    networks:
      backend:
# リバプロ用      
#      proxy-network:
volumes:
  v-postgres:
networks:
  backend:
# リバプロ用      
#  proxy_network:
#    external: true
