version: '3'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:3.4.3.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080
    networks:
      backend:
  postgres:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - v-postgres:/var/lib/postgresql/
    networks:
      backend:
volumes:
  v-postgres:
networks:
  backend: